#!/usr/bin/python

import sys
import os
import glob

usage = '''
    suport build and clean.
    build will produce executable to the bin folder
    clean will delete all file in bin
    example:
    haskell build [filename, [filename...]]
    haskell clean
'''


destination = os.getcwd() + '/../bin/';
def build():
    if sys.argv < 3:
        print 'mising file name\n'
        return

    files = sys.argv[2:]

    for filename in files:
        command = ['ghc'] + [filename] + ['-o'] + [destination + filename.split('.')[0]]
        print (' '.join(command))
        os.system(' '.join(command))
        
    #clean up    
    files = glob.glob(os.getcwd()+'/*.hi') + glob.glob(os.getcwd()+'/*.o')
    for filename in files:
        os.remove(filename)
        
def clean():
    os.chdir(destination)
    files = glob.glob('*')
    for filename in files:
        os.remove(filename)

#main#
if len(sys.argv) < 2:
    print usage
    sys.exit(1)
    
token = sys.argv[1]
if token == 'build':
    build()
elif token == 'clean':
    clean()
else:
    print usage
    sys.exit(1)
    
        


        
        


